services:
  server:
    build:
      context: .
      args:
        GOARCH: ${GOARCH}
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    environment:
      - HTTP_PORT=${CONTAINER_PORT}
      - ALLOW_EMPTY_REQUEST_ID=${ALLOW_EMPTY_REQUEST_ID}
      - SERVICE_NAME=${SERVICE_NAME}
      - OTLP_EXPORTER_ENDPOINT=${OTLP_EXPORTER_ENDPOINT}
      - OTLP_EXPORTER_INSECURE=${OTLP_EXPORTER_INSECURE}
