version: "3.8"

services:
  server:
    build:
      context: .
      args:
        GOARCH: ${GOARCH}
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    environment:
      - HTTP_PORT=${CONTAINER_PORT}
