version: "3.8"

services:
  server:
    build:
      context: .
      args:
        GOARCH: ${GOARCH}
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
    environment:
      - PORT=${INTERNAL_PORT}
