package config

import (
	"encoding/json"

	"connectrpc.com/connect"

	"github.com/eljamo/libpass/v5/asset"
	"github.com/eljamo/libpass/v5/config"
	"github.com/eljamo/libpass/v5/config/option"

	mempassv1 "github.com/eljamo/mempass-api/internal/gen/mempass/v1" // generated by protoc-gen-connect-go
)

func Generate(req *connect.Request[mempassv1.GeneratePasswordsRequest]) (*config.Settings, error) {
	basePreset, err := loadJSONFiles(req)
	if err != nil {
		return nil, err
	}

	var cfg map[string]any
	msg, err := json.Marshal(req.Msg)
	if err != nil {
		return nil, err
	}
	if err := json.Unmarshal(msg, &cfg); err != nil {
		return nil, err
	}

	return config.Generate(basePreset, cfg)
}

func loadJSONFiles(req *connect.Request[mempassv1.GeneratePasswordsRequest]) (map[string]any, error) {
	presetValue, err := getPresetValue(req)
	if err != nil {
		return nil, err
	}

	basePreset, err := asset.GetJSONPreset(presetValue)
	if err != nil {
		return nil, err
	}

	return basePreset, nil
}

func getPresetValue(req *connect.Request[mempassv1.GeneratePasswordsRequest]) (string, error) {
	presetValue := req.Msg.GetPreset()

	if presetValue == "" {
		presetValue = option.Default
	}

	return presetValue, nil
}
